Executa comandos a partir da pasta do projeto
PHPRio/novo-site pull request #17
Opened 2023-12-13 05:52 UTC by lhsazevedo

Fixes #13.

2023-12-13 12:12 UTC, giovannism20 requested changes

2023-12-14 11:45 UTC, lhsazevedo commented
Isso que dá codar de madrugada rs
Vou corrigir em breve

2023-12-19 21:08 UTC, giovannism20 approved these changes

2023-12-19 21:20 UTC, vitormattos approved these changes

2023-12-19 21:26 UTC, merged